### ISSUE TITLE
User Registration needs to validate email address (Frontend)

### ISSUE THREAD

**Issue by FredrikEH** [boolean-uk/team-dev-client-ex-2410-team3#27]
EPIC: https://github.com/boolean-uk/team-dev-client-ex-2410-team3/issues/9

When a user creates a new account, they fill in an email and password. The app should validate the below conditions before letting the account be created, displaying a user friendly message if any check fails:

- The email address must not already be in use

- [x] Add functionality to check if email already exist, get information from database.  
Possible solutions:  
```
Solution 1.)
In auth.js

handleRegister():
- Check if response from register() returns error. (If the backend don't allow duplication of email)
- Return to Registration page and give the user a message about the error.
```

```
Solution 2.)
Check if email exists before the user clicks on the `Sign up` button.
```

- The email address must be in a valid format (e.g. abc@abc)
- [x] Add `type=email` to input attribute 
```
<div className="login-form">
          <form>
            <TextInput value={formData.email} onChange={onChange} name="email" type="email" label={'Email *'} />
           ......
```

**Comment by amos1969** [comment]
Approved

**Comment by shyye** [comment]
- 'Check if Email already Exists' is checked by getting the json response from the register() funcition.
- If email already exists the error message is sent back to the UI.
- A component for the error message is created in components/errorMessage
NOTE: The component width is 'full width/100%', it may be an issue on large components, consider adding a max-width if necessary.
- The user feedback provided through the TextInput component could be improved but I leave it as is for now because another person is working on that component at the moment.
